build:
  version: "3.0"

accounts:
  message: "Welcome to Romeos-code loans related local APIs "
  contactDetails:
    name: "Romeo Jerenyama - Developer"
    email: "romeojerenyama@gmail.com"
  onCallSupport:
    - (+351) 968-680-744
